import {
  addShoppingItem,
  addManyShoppingItems,
  addDishIngredientsToShoppingList,
  addRecipeIngredientsToShoppingList,
  appendToRecentDish,
  checkInKitchenItem,
  checkInManyKitchenItems,
  clearKitchenInventory,
  clearRecentDiscards,
  clearShoppingList,
  deleteRecentDiscard,
  deleteDishLog,
  discardKitchenItem,
  getHealthMetrics,
  getDishDetail,
  getKitchenOverview,
  getMealPlan,
  getRecentDiscards,
  getRecentDishes,
  getRecipeDetail,
  getRecipeSuggestions,
  getShoppingItems,
  listStoreTabs,
  logDishFromVoice,
  logDishIngredients,
  markDishConsumed,
  markKitchenItemOpened,
  markShoppingItemBought,
  markShoppingItemUnbought,
  removeShoppingItem,
  recommendItemsToBuy,
  recommendItemsToUseUp,
  refreshMealPlan,
  searchKitchenItem,
  updateKitchenItemDetails,
  updateKitchenItemExpiration,
  updateKitchenItemLocation,
  updateKitchenItemQuantity,
  updateRecentDish,
  updateManyShoppingItemStores,
  updateShoppingItemStore
} from "./data-access.mjs";
import {
  buildMockToolResult,
  createToolActionExecutor,
  formatActionDetails,
  formatActionSummary,
  humanizePrimaryEntity,
  toTitleCase,
  validateToolCall
} from "../../shared/voice-assistant/tool-executor.mjs";

export { buildMockToolResult, formatActionDetails, formatActionSummary, toTitleCase, validateToolCall };

export function humanizeItemName(args) {
  return humanizePrimaryEntity(args);
}

async function unsupportedSavedRecipeAction() {
  throw new Error("Saved recipe tools are not supported in realtime-kitchen-voice-test.");
}

export const executeToolAction = createToolActionExecutor({
  addShoppingItem,
  addManyShoppingItems,
  updateShoppingItemStore,
  updateManyShoppingItemStores,
  markShoppingItemBought,
  markShoppingItemUnbought,
  removeShoppingItem,
  clearShoppingList,
  getShoppingItems,
  listStoreTabs,
  getKitchenOverview,
  getRecentDiscards,
  searchKitchenItem,
  checkInKitchenItem,
  checkInManyKitchenItems,
  updateKitchenItemQuantity,
  markKitchenItemOpened,
  updateKitchenItemExpiration,
  updateKitchenItemLocation,
  updateKitchenItemDetails,
  discardKitchenItem,
  clearKitchenInventory,
  deleteRecentDiscard,
  clearRecentDiscards,
  logDishFromVoice,
  logDishIngredients,
  appendToRecentDish,
  updateRecentDish,
  getRecentDishes,
  getDishDetail,
  markDishConsumed,
  deleteDishLog,
  addDishIngredientsToShoppingList,
  addRecipeIngredientsToShoppingList,
  addSavedRecipeIngredientsToShoppingList: unsupportedSavedRecipeAction,
  getHealthMetrics,
  getRecipeSuggestions,
  getRecipeDetail,
  getSavedRecipes: unsupportedSavedRecipeAction,
  getSavedRecipeDetail: unsupportedSavedRecipeAction,
  saveRecipeFromTikTok: unsupportedSavedRecipeAction,
  saveGeneratedRecipe: unsupportedSavedRecipeAction,
  removeSavedRecipe: unsupportedSavedRecipeAction,
  getMealPlan,
  refreshMealPlan,
  recommendItemsToBuy,
  recommendItemsToUseUp
});
