import {
  addShoppingItem,
  addManyShoppingItems,
  addDishIngredientsToShoppingList,
  addRecipeIngredientsToShoppingList,
  addSavedRecipeIngredientsToShoppingList,
  appendToRecentDish,
  checkInKitchenItem,
  checkInManyKitchenItems,
  clearKitchenInventory,
  clearRecentDiscards,
  clearShoppingList,
  deleteRecentDiscard,
  deleteDishLog,
  discardKitchenItem,
  getHealthMetrics,
  getDishDetail,
  getKitchenOverview,
  getMealPlan,
  getRecentDiscards,
  getRecentDishes,
  getRecipeDetail,
  getRecipeSuggestions,
  getSavedRecipeDetail,
  getSavedRecipes,
  getShoppingItems,
  listStoreTabs,
  logDishFromVoice,
  logDishIngredients,
  markDishConsumed,
  markKitchenItemOpened,
  markShoppingItemBought,
  markShoppingItemUnbought,
  removeShoppingItem,
  recommendItemsToBuy,
  recommendItemsToUseUp,
  removeSavedRecipe,
  refreshMealPlan,
  searchKitchenItem,
  searchWebRecipes,
  saveRecipeFromTikTok,
  saveGeneratedRecipe,
  updateKitchenItemDetails,
  updateKitchenItemExpiration,
  updateKitchenItemLocation,
  updateKitchenItemQuantity,
  updateRecentDish,
  updateManyShoppingItemStores,
  updateShoppingItemStore
} from "./data-access.mjs";
import {
  buildMockToolResult,
  createToolActionExecutor,
  formatActionDetails,
  formatActionSummary,
  humanizePrimaryEntity,
  toTitleCase,
  validateToolCall
} from "../../../shared/voice-assistant/tool-executor.mjs";

export { buildMockToolResult, formatActionDetails, formatActionSummary, toTitleCase, validateToolCall };

export function humanizeItemName(args) {
  return humanizePrimaryEntity(args);
}

export const executeToolAction = createToolActionExecutor({
  addShoppingItem,
  addManyShoppingItems,
  updateShoppingItemStore,
  updateManyShoppingItemStores,
  markShoppingItemBought,
  markShoppingItemUnbought,
  removeShoppingItem,
  clearShoppingList,
  getShoppingItems,
  listStoreTabs,
  getKitchenOverview,
  getRecentDiscards,
  searchKitchenItem,
  searchWebRecipes,
  checkInKitchenItem,
  checkInManyKitchenItems,
  updateKitchenItemQuantity,
  markKitchenItemOpened,
  updateKitchenItemExpiration,
  updateKitchenItemLocation,
  updateKitchenItemDetails,
  discardKitchenItem,
  clearKitchenInventory,
  deleteRecentDiscard,
  clearRecentDiscards,
  logDishFromVoice,
  logDishIngredients,
  appendToRecentDish,
  updateRecentDish,
  getRecentDishes,
  getDishDetail,
  markDishConsumed,
  deleteDishLog,
  addDishIngredientsToShoppingList,
  addRecipeIngredientsToShoppingList,
  addSavedRecipeIngredientsToShoppingList,
  getHealthMetrics,
  getRecipeSuggestions,
  getRecipeDetail,
  getSavedRecipes,
  getSavedRecipeDetail,
  saveRecipeFromTikTok,
  saveGeneratedRecipe,
  removeSavedRecipe,
  getMealPlan,
  refreshMealPlan,
  recommendItemsToBuy,
  recommendItemsToUseUp
});
