const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../candidates/getJob');
function handler(job){let reads=0;const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'getJob/app.js'),'utf8'),{module,exports:module.exports,console:{log(){},error(){}},require:name=>{if(name==='../dist/utils/jobQueue')return {getJob:async id=>{reads++;assert.equal(id,'job-1');return job;}};if(name==='../emptyBulkOutcome')return require(path.join(root,'emptyBulkOutcome'));throw Error('Unexpected dependency '+name);}});return {run:async()=>{const res=await module.exports.handler({pathParameters:{job_id:'job-1'}});return {...res,json:JSON.parse(res.body)};},get reads(){return reads;}};}
const job=(overrides={})=>({job_id:'job-1',status:'completed',analysis_mode:'bulk_inventory_deep',stage:'completed',stage_message:'No items identified',progress:100,meta:{owner:'owner-A'},result:{items:[]},...overrides});
test('legacy completed empty bulk projects failed on successful HTTP for 1.16 polling without mutating source',async()=>{const row=job(),before=structuredClone(row),h=handler(row);for(let i=0;i<2;i++){const res=await h.run();assert.equal(res.statusCode,200);assert.equal(res.json.status,'failed');assert.equal(res.json.stage,'failed');assert.equal(res.json.result.error_code,'no_items_identified');assert.match(res.json.error,/No grocery items/);}assert.deepEqual(row,before);assert.equal(h.reads,2);});
test('new empty-bulk failure remains HTTP200 while generic provider failure keeps HTTP500',async()=>{const empty=await handler(job({status:'failed',result:{items:[],error_code:'no_items_identified'},error:'No grocery items were found. Try a clearer photo.'})).run();assert.equal(empty.statusCode,200);assert.equal(empty.json.status,'failed');const generic=await handler(job({status:'failed',result:null,error:'provider unavailable'})).run();assert.equal(generic.statusCode,500);assert.equal(generic.json.error,'provider unavailable');});
for(const mode of ['receipt_inventory_deep','quick_identify_deep','product_analysis'])test('empty '+mode+' retains existing completed semantics',async()=>{const row=job({analysis_mode:mode,result:{items:[],capture_outcomes:[{status:'no_food'}]}});const res=await handler(row).run();assert.equal(res.statusCode,200);assert.equal(res.json.status,'completed');assert.deepEqual(res.json.result,row.result);});
test('nonempty bulk retains exact result, status and owner',async()=>{const row=job({result:{items:[{item_name:'Milk',count:1}]},stage_message:'Ready to review'});const res=await handler(row).run();assert.equal(res.statusCode,200);assert.equal(res.json.status,'completed');assert.deepEqual(res.json.result,row.result);assert.deepEqual(res.json.meta,row.meta);});
test('pending and processing stay accepted even with intermediate empty items',async()=>{for(const status of ['pending','processing']){const res=await handler(job({status})).run();assert.equal(res.statusCode,202);assert.equal(res.json.status,status);}});
test('absent malformed result and committed history are not reinterpreted as a detected empty result',async()=>{for(const override of [{result:null},{result:{}},{result:{items:'invalid'}},{commit_status:'committed'}]){const res=await handler(job(override)).run();assert.equal(res.statusCode,200);assert.equal(res.json.status,'completed');}});
test('missing job remains404 and never creates a replacement',async()=>{const h=handler(null),res=await h.run();assert.equal(res.statusCode,404);assert.equal(h.reads,1);});
