const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{randomUUID,createHmac}=require('node:crypto');
const root=path.resolve(__dirname,'../baseline/getSessions'),load=require('node:module').createRequire(path.join(root,'package.json'));
Object.assign(process.env,{AWS_ENDPOINT_URL_DYNAMODB:'http://127.0.0.1:38001',AWS_ACCESS_KEY_ID:'fixture',AWS_SECRET_ACCESS_KEY:'fixture',AWS_REGION:'us-east-1',TOKEN_SIGNING_SECRET:'empty-bulk-isolated-fixture',JOB_TABLE_NAME:'empty_inbox_'+randomUUID().replaceAll('-',''),SESSION_TABLE_NAME:'empty_session_'+randomUUID().replaceAll('-','')});
const aws=load('@aws-sdk/client-dynamodb'),docmod=load('@aws-sdk/lib-dynamodb');const raw=new aws.DynamoDBClient({}),doc=docmod.DynamoDBDocumentClient.from(raw);
const handler=load('./getSessions/app').handler;const {reviewIndexFields}=load('./reviewInbox');
before(async()=>{await raw.send(new aws.CreateTableCommand({TableName:process.env.JOB_TABLE_NAME,BillingMode:'PAY_PER_REQUEST',KeySchema:[{AttributeName:'job_id',KeyType:'HASH'}],AttributeDefinitions:[{AttributeName:'job_id',AttributeType:'S'},{AttributeName:'review_owner',AttributeType:'S'},{AttributeName:'review_order',AttributeType:'S'}],GlobalSecondaryIndexes:[{IndexName:'review-owner-index',KeySchema:[{AttributeName:'review_owner',KeyType:'HASH'},{AttributeName:'review_order',KeyType:'RANGE'}],Projection:{ProjectionType:'KEYS_ONLY'}}]}));await raw.send(new aws.CreateTableCommand({TableName:process.env.SESSION_TABLE_NAME,BillingMode:'PAY_PER_REQUEST',KeySchema:[{AttributeName:'session_id',KeyType:'HASH'}],AttributeDefinitions:[{AttributeName:'session_id',AttributeType:'S'},{AttributeName:'owner_id',AttributeType:'S'}],GlobalSecondaryIndexes:[{IndexName:'owner-index',KeySchema:[{AttributeName:'owner_id',KeyType:'HASH'}],Projection:{ProjectionType:'ALL'}}]}));});
after(async()=>{for(const TableName of [process.env.JOB_TABLE_NAME,process.env.SESSION_TABLE_NAME])await raw.send(new aws.DeleteTableCommand({TableName}));raw.destroy();});
function event(owner,{signedOwner=owner,query={},unsigned=false}={}){const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url'),h=enc({alg:'HS256'}),b=enc({iss:'trepo-auth',user_id:signedOwner,exp:Date.now()/1000+600}),sig=createHmac('sha256',process.env.TOKEN_SIGNING_SECRET).update(h+'.'+b).digest('base64url');return {pathParameters:{owner_id:owner},queryStringParameters:{review:'1',...query},headers:unsigned?{}:{Authorization:'Bearer '+h+'.'+b+'.'+sig}};}
async function put(owner,overrides={}){const row={job_id:randomUUID(),created_at:new Date().toISOString(),status:'completed',analysis_mode:'bulk_inventory_deep',meta:{owner,persist_to_kitchen:false},result:{items:[]},...overrides};Object.assign(row,reviewIndexFields(row));await doc.send(new docmod.PutCommand({TableName:process.env.JOB_TABLE_NAME,Item:row}));return row;}
async function get(id){return (await doc.send(new docmod.GetCommand({TableName:process.env.JOB_TABLE_NAME,Key:{job_id:id},ConsistentRead:true}))).Item;}
test('actual deployed discovery omits already-completed empty bulk and preserves stored jobs',async()=>{const owner=randomUUID(),empty=await put(owner),valid=await put(owner,{result:{items:[{item_name:'Milk'}]}});const res=await handler(event(owner));assert.equal(res.statusCode,200);assert.deepEqual(JSON.parse(res.body).jobs.map(j=>j.job_id),[valid.job_id]);assert.deepEqual(await get(empty.job_id),empty);assert.deepEqual(await get(valid.job_id),valid);});
test('actual deployed discovery is owner-scoped and rejects unsigned or cross-owner requests',async()=>{const owner=randomUUID(),foreign=randomUUID();const own=await put(owner,{result:{items:[{item_name:'Own'}]}}),other=await put(foreign,{result:{items:[{item_name:'Other'}]}});await doc.send(new docmod.UpdateCommand({TableName:process.env.JOB_TABLE_NAME,Key:{job_id:other.job_id},UpdateExpression:'SET review_owner=:owner',ExpressionAttributeValues:{':owner':owner}}));assert.equal((await handler(event(owner,{unsigned:true}))).statusCode,401);assert.equal((await handler(event(owner,{signedOwner:foreign}))).statusCode,403);assert.deepEqual(JSON.parse((await handler(event(owner))).body).jobs.map(j=>j.job_id),[own.job_id]);assert.equal((await get(other.job_id)).meta.owner,foreign);});
test('empty filtered page keeps cursor so a subsequent valid job is discoverable; cursor cannot cross owner',async()=>{const owner=randomUUID();const valid=await put(owner,{created_at:'2026-01-01T00:00:00Z',result:{items:[{item_name:'Valid earlier'}]}});await put(owner,{created_at:'2026-01-02T00:00:00Z'});const first=JSON.parse((await handler(event(owner,{query:{limit:'1'}}))).body);assert.deepEqual(first.jobs,[]);assert.ok(first.next_cursor);const next=await handler(event(owner,{query:{cursor:first.next_cursor,limit:'1'}}));assert.deepEqual(JSON.parse(next.body).jobs.map(j=>j.job_id),[valid.job_id]);assert.equal((await handler(event(randomUUID(),{query:{cursor:first.next_cursor}}))).statusCode,400);});
test('pending and processing remain discoverable while failed empty jobs do not',async()=>{const owner=randomUUID(),expected=[];for(const status of ['pending','processing','failed']){const row=await put(owner,{status});if(status!=='failed')expected.push(row.job_id);}assert.deepEqual(new Set(JSON.parse((await handler(event(owner))).body).jobs.map(j=>j.job_id)),new Set(expected));});
test('legacy sessions path preserves owner query and its existing payload without introducing customer writes',async()=>{const owner=randomUUID(),foreign=randomUUID(),own={session_id:randomUUID(),owner_id:owner,status:'processing',job_ids:['empty','valid'],completed_job_ids:['empty','valid'],failed_job_ids:[],total_jobs:2};for(const row of [own,{...own,session_id:randomUUID(),owner_id:foreign}])await doc.send(new docmod.PutCommand({TableName:process.env.SESSION_TABLE_NAME,Item:row}));const res=await handler({pathParameters:{owner_id:owner},headers:{},queryStringParameters:{}});assert.equal(res.statusCode,200);assert.deepEqual(JSON.parse(res.body).sessions,[own]);assert.deepEqual((await doc.send(new docmod.GetCommand({TableName:process.env.SESSION_TABLE_NAME,Key:{session_id:own.session_id}}))).Item,own);});
